services:
  db:
    image: postgres:17
    container_name: simple-online-store-db
    restart: always
    networks:
      - app_network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 3dxlq0tj
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge

volumes:
  db_data: