/* tslint:disable */
/* eslint-disable */
/**
 * SimpleOnlineStoreApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProductDto
 */
export interface CreateProductDto {
    /**
     * 
     * @type {string}
     * @memberof CreateProductDto
     */
    brand?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateProductDto
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateProductDto
     */
    price?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CreateProductDto
     */
    isNew?: boolean;
}

/**
 * Check if a given object implements the CreateProductDto interface.
 */
export function instanceOfCreateProductDto(value: object): value is CreateProductDto {
    return true;
}

export function CreateProductDtoFromJSON(json: any): CreateProductDto {
    return CreateProductDtoFromJSONTyped(json, false);
}

export function CreateProductDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProductDto {
    if (json == null) {
        return json;
    }
    return {
        
        'brand': json['brand'] == null ? undefined : json['brand'],
        'name': json['name'] == null ? undefined : json['name'],
        'price': json['price'] == null ? undefined : json['price'],
        'isNew': json['isNew'] == null ? undefined : json['isNew'],
    };
}

export function CreateProductDtoToJSON(json: any): CreateProductDto {
    return CreateProductDtoToJSONTyped(json, false);
}

export function CreateProductDtoToJSONTyped(value?: CreateProductDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'brand': value['brand'],
        'name': value['name'],
        'price': value['price'],
        'isNew': value['isNew'],
    };
}

