// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimpleOnlineStoreApi.DAL;

#nullable disable

namespace SimpleOnlineStoreApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250317171430_AddDescriptionFieldToProduct")]
    partial class AddDescriptionFieldToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimpleOnlineStoreApi.Entities.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Apple",
                            Description = "iPhone 11 Pro — это премиальный смартфон от Apple, представленный в 2019 году. Он оснащён 5,8-дюймовым Super Retina XDR дисплеем, который обеспечивает яркие цвета, глубокий чёрный цвет и высокую детализацию.\n\n🔥 Основные характеристики:\nПроцессор: Apple A13 Bionic — быстрый и энергоэффективный чип\nДисплей: 5,8\" OLED Super Retina XDR (разрешение 2436×1125)\nКамеры:\n📸 Тройная основная камера (12 МП):\nШирокоугольная (f/1.8)\nСверхширокоугольная (f/2.4, угол обзора 120°)\nТелеобъектив (f/2.0, 2× оптический зум)\n📸 Фронтальная камера 12 МП с поддержкой Night Mode и 4K-видео\nАвтономность: До 4 часов дольше, чем iPhone XS\nМатериалы: Корпус из стекла и хирургической нержавеющей стали\nЗащита: Водонепроницаемость IP68 (до 4 метров на 30 минут)\nОперационная система: iOS (с возможностью обновления до последних версий)\nДоступен в цветах: Midnight Green, Space Gray, Silver, Gold.\n\niPhone 11 Pro остаётся мощным и актуальным смартфоном даже спустя годы благодаря производительности и качеству камер. 🚀",
                            IsNew = false,
                            Name = "iPhone 11 Pro",
                            Price = 29990m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
